version: '3.8'

services:
  app:
    container_name: nodejs-bff
    image: node:20-alpine
    working_dir: /usr/src/app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - .env:/usr/src/app/.env
    ports:
      - "${PORT:-3300}:${PORT:-3300}"
    command: npm run start:dev

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  elasticmq:
    image: softwaremill/elasticmq
    container_name: elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    environment:
      - ELASTICMQ_REST_PORT=9324
    command: -Dconfig.file=/opt/elasticmq.conf

volumes:
  mysql-data:
