version: '3.8'

services:
  app:
    container_name: nodejs-bff
    image: node:20-alpine
    working_dir: /usr/src/app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - .env:/usr/src/app/.env
    ports:
      - "${PORT:-3300}:${PORT:-3300}"
    command: npm run start:dev

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
